### ISSUE TITLE
The request body must contain the following parameter: 'client_assertion' or 'client_secret'

### ISSUE THREAD

**Issue by leo-coco** [joelmeiller/cypress-msal-login#7]
Hi there,

I'm trying to use your package to log in MSAL. I have the bellowing error

`error_description": "AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'`

Could you please add `client_secret` to the `auth` parameters?

**Comment by GLObus303** [comment]
You can use `options` parameter. Since it uses lodashe's [extend](https://www.geeksforgeeks.org/lodash-_-extend-method/) you will have to rebuild the whole body.

I kinda find this very cumbersome so I've created this PR which also fixes some logger errors

**Comment by AlfonsoFlorioAngstrom** [comment]
> You can use `options` parameter. Since it uses lodashe's [extend](https://www.geeksforgeeks.org/lodash-_-extend-method/) you must rebuild the whole body.
> 
> I find this very cumbersome. I would suggest using some "customBodyOptions". Do you take contributions @joelmeiller? There are also some logger errors in the app, I would fix them

Can you provide a full example? Also I don't understand what you mean by "you must rebuild the whole body" I am trying with a structure like below but I keep getting the same error.

`      {
        username: 'alfonso.florio@*',
        password: '***',
        options: {
          client_secret:'***',
          client_assert:'***'
        }
      },`

**Comment by GLObus303** [comment]
@AlfonsoFlorioAngstrom 

This line https://github.com/joelmeiller/cypress-msal-login/blob/main/src/index.ts#L79 is fusing inner `options` object with first parameter's `options`

```
cy.msalLogin(
  {
    email: 'my-test-user@cypress.com',
    password: 'whatever'
   options: { ... } <- here
  },
...)
```

But, if you are going to pass anything in the nested `body` object. You MUST also pass all of the [other](https://github.com/joelmeiller/cypress-msal-login/blob/main/src/index.ts#L68-L75) parameters

The problem on your code is 

1. `client_assert` -> `client_assertion` but I believe it is just a typo in the comment
2. you must nest these into `body` object, so it would look something like this ``` { username: 'alfonso.florio@*', password: '***', options: { body: { client_secret:'***', client_assert:'***' } } }, ```

But the problem with the nesting is my aforementioned `"you must rebuild the whole body"` because the result of the updated snippet with `options: { body: ...` would look like this


```
const options = {
      method: 'POST',
      url: AzureTokenUrl,
      form: true,
      body: {
       client_secret:'***', 
       client_assert:'***' 
      },
    }
```


So in order to make it complete, I think this should be enough:

```
 { username: 'alfonso.florio@*', 
   password: '***', 
  options: { 
       body: { 
           client_secret:'***',
           client_assert:'***'
           grant_type: 'password', 
           client_id: <your_client_id>
           client_info: 1,
           scope:  scopes.join(' '), <- your scopes
           username:'alfonso.florio@*',
          password: '***', 
 } } }, ```


I hope it helps. Happy hacking

**Comment by AlfonsoFlorioAngstrom** [comment]
@GLObus303 Thank you a million. yes, this really helps a lot. Not been successful yet in login but at least I have all the pieces here

**Comment by joelmeiller** [comment]
@GLObus303 Thanks a lot for your support. 🙏🏻 and I invited you know as collaborator.

**Comment by joelmeiller** [comment]
Closing this issue as I think it's solved and the questions answered
